-- CreateEnum
CREATE TYPE "Category" AS ENUM ('EDUCATION', 'SCIENCE_TECH', 'ENTERTAINMENT', 'MUSIC', 'BUSINESS', 'HEALTH_FITNESS', 'COOKING', 'LANGUAGE', 'ARTS_CRAFTS', 'OTHER');

-- AlterTable
ALTER TABLE "SubHub" ADD COLUMN     "category" "Category" NOT NULL DEFAULT 'OTHER';
